apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-chart.fullname" . }}-service-gateway
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}-service-gateway
spec:
  selector:
    {{- include "backend-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.port }}
  type: {{ .Values.gateway.service.type }}