apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}-service
spec:
  selector:
    {{- include "backend-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
  