apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-chart.fullname" . }}-service
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}-service
spec:
  selector:
    {{- include "backend-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.backend.port }}
  type: {{ .Values.service.type }}