apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-chart.fullname" . }}-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "jdbc:postgresql://%s-postgresql:%s/%s" (include "backend-chart.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  DATABASE_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}