apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backend-chart.fullname" . }}-app-ingress
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-url: "http://192.168.64.5/auth/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://192.168.64.5/auth/signin"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-UserId,X-Username"
spec:
  rules:
    - host: {{ .Values.nginx.host }}
      http:
        paths:
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "backend-chart.fullname" . }}-app-service
                port:
                  number: {{ .Values.serviceApp.port }}