apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-chart.fullname" . }}-app-service
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}-app-service
spec:
  selector:
    {{- include "backend-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.serviceApp.port }}
      targetPort: {{ .Values.backendApp.port }}
  type: {{ .Values.serviceApp.type }}