replicaCount: 2

image:
  repository: devsnice/arch:v1-crud

backend:
  port: 8080

service:
  type: NodePort
  port: 80

nginx:
  host: arch.homework

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"